{% set name = "pandas-profiling" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 258d849d7bd398cc4180ddfe9f484077562d1cb7945ef37f1c140d514050ef8c

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python >=2.7
    - scipy >=1.3
    - requests >=2.22
    - missingno >=0.4
    - pandas >=0.19
    - matplotlib >=1.4
    - jinja2 >=2.8
    - htmlmin >=0.1
    - phik >=0.9
    - confuse >=1.0

test:
  imports:
    - pandas_profiling

about:
  home: http://github.com/jospolfliet/pandas-profiling
  license: MIT
  license_file: LICENSE
  summary: 'Generate profile report for pandas DataFrame'
  dev_url: http://github.com/jospolfliet/pandas-profiling

extra:
  recipe-maintainers:
    - proinsias
